version: 3
allow:
  depOnAnyVendor: true
  deepScan: true
excludeFiles:
  - "yap/.+"
  - "references/.+"
  - "\\.worktrees/.+"
  - "readme_test\\.go"

components:
  cmd:
    in: cmd/**
  internal:
    in: internal/**
  pkg:
    in: pkg/**

deps:
  cmd:
    mayDependOn:
      - internal
      - pkg
  internal:
    mayDependOn:
      - internal
      - pkg
  pkg:
    mayDependOn:
      - pkg
