version: 3
allow:
  depOnAnyVendor: true
excludeFiles:
  - "yap/.+"
  - "references/.+"

components:
  cmd:
    in: cmd/**
  internal:
    in: internal/**
  pkg:
    in: pkg/**

deps:
  cmd:
    mayDependOn:
      - internal
      - pkg
  internal:
    mayDependOn:
      - internal
      - pkg
