# Oro golangci-lint configuration (v2 format)
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Correctness
    - staticcheck
    - govet
    - ineffassign
    - unused
    - errcheck

    # Error handling
    - errorlint
    - wrapcheck

    # Complexity
    - gocyclo
    - gocognit
    - funlen
    - nestif

    # Structure
    - gochecknoglobals
    - gochecknoinits
    - testpackage

    # Security
    - gosec

    # Style
    - gocritic
    - revive
    - misspell

  settings:
    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 30

    funlen:
      lines: 60
      statements: 40
      ignore-comments: true

    nestif:
      min-complexity: 4

    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close

    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Join(

  exclusions:
    generated: lax
    presets:
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - funlen
          - gocyclo
          - gocognit
          - gochecknoglobals
          - wrapcheck

      - path: main\.go
        linters:
          - gochecknoinits
          - gochecknoglobals


formatters:
  enable:
    - goimports
