# Oro golangci-lint configuration — start strict, expand incrementally.
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # Correctness
    - staticcheck
    - govet
    - ineffassign
    - unused
    - errcheck

    # Error handling
    - errorlint
    - wrapcheck

    # Complexity
    - gocyclo
    - gocognit
    - funlen
    - nestif

    # Structure
    - gochecknoglobals
    - gochecknoinits
    - testpackage

    # Security
    - gosec

    # Style
    - gocritic
    - revive
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 10

  gocognit:
    min-complexity: 10

  funlen:
    lines: 60
    statements: 40
    ignore-comments: true

  nestif:
    min-complexity: 4

  errcheck:
    check-type-assertions: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  wrapcheck:
    ignore-sigs:
      - .Errorf(
      - errors.New(
      - errors.Join(

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gochecknoglobals
        - wrapcheck

    - path: main\.go
      linters:
        - gochecknoinits
        - gochecknoglobals

  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - goimports
